//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18063.
// 
#pragma warning disable 1591

namespace Evoluciona.Dialogo.Web.WsDirectorio {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProcesoDIRWebServiceSoapBinding", Namespace="http://pelnx12.galileo.ebel:7777/ssiccpeesprd/services/ProcesoDIRWebService")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ClienteDIRWebService))]
    public partial class ProcesoDIRWebServiceImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obtenerClientesDirectorioOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarClientesDirectorioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProcesoDIRWebServiceImplService() {
            this.Url = global::Evoluciona.Dialogo.Web.Properties.Settings.Default.Evoluciona_Dialogo_Web_WsDirectorio_ProcesoDIRWebServiceImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obtenerClientesDirectorioCompletedEventHandler obtenerClientesDirectorioCompleted;
        
        /// <remarks/>
        public event buscarClientesDirectorioCompletedEventHandler buscarClientesDirectorioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://impl.ws.dir.ssicc.belcorp.biz", ResponseNamespace="http://pelnx12.galileo.ebel:7777/ssiccpeesprd/services/ProcesoDIRWebService")]
        [return: System.Xml.Serialization.SoapElementAttribute("obtenerClientesDirectorioReturn")]
        public ProcesoDIRWebServiceResultado obtenerClientesDirectorio(string codigoPais, string codigoRegion, string codigoZona, string codigoTipoCargo, string codigoPeriodo, string estadoCargo) {
            object[] results = this.Invoke("obtenerClientesDirectorio", new object[] {
                        codigoPais,
                        codigoRegion,
                        codigoZona,
                        codigoTipoCargo,
                        codigoPeriodo,
                        estadoCargo});
            return ((ProcesoDIRWebServiceResultado)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerClientesDirectorioAsync(string codigoPais, string codigoRegion, string codigoZona, string codigoTipoCargo, string codigoPeriodo, string estadoCargo) {
            this.obtenerClientesDirectorioAsync(codigoPais, codigoRegion, codigoZona, codigoTipoCargo, codigoPeriodo, estadoCargo, null);
        }
        
        /// <remarks/>
        public void obtenerClientesDirectorioAsync(string codigoPais, string codigoRegion, string codigoZona, string codigoTipoCargo, string codigoPeriodo, string estadoCargo, object userState) {
            if ((this.obtenerClientesDirectorioOperationCompleted == null)) {
                this.obtenerClientesDirectorioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerClientesDirectorioOperationCompleted);
            }
            this.InvokeAsync("obtenerClientesDirectorio", new object[] {
                        codigoPais,
                        codigoRegion,
                        codigoZona,
                        codigoTipoCargo,
                        codigoPeriodo,
                        estadoCargo}, this.obtenerClientesDirectorioOperationCompleted, userState);
        }
        
        private void OnobtenerClientesDirectorioOperationCompleted(object arg) {
            if ((this.obtenerClientesDirectorioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerClientesDirectorioCompleted(this, new obtenerClientesDirectorioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://impl.ws.dir.ssicc.belcorp.biz", ResponseNamespace="http://pelnx12.galileo.ebel:7777/ssiccpeesprd/services/ProcesoDIRWebService")]
        [return: System.Xml.Serialization.SoapElementAttribute("buscarClientesDirectorioReturn")]
        public ProcesoDIRWebServiceResultado buscarClientesDirectorio(string codigoPais, string usuarioRed, string codigoCUB) {
            object[] results = this.Invoke("buscarClientesDirectorio", new object[] {
                        codigoPais,
                        usuarioRed,
                        codigoCUB});
            return ((ProcesoDIRWebServiceResultado)(results[0]));
        }
        
        /// <remarks/>
        public void buscarClientesDirectorioAsync(string codigoPais, string usuarioRed, string codigoCUB) {
            this.buscarClientesDirectorioAsync(codigoPais, usuarioRed, codigoCUB, null);
        }
        
        /// <remarks/>
        public void buscarClientesDirectorioAsync(string codigoPais, string usuarioRed, string codigoCUB, object userState) {
            if ((this.buscarClientesDirectorioOperationCompleted == null)) {
                this.buscarClientesDirectorioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarClientesDirectorioOperationCompleted);
            }
            this.InvokeAsync("buscarClientesDirectorio", new object[] {
                        codigoPais,
                        usuarioRed,
                        codigoCUB}, this.buscarClientesDirectorioOperationCompleted, userState);
        }
        
        private void OnbuscarClientesDirectorioOperationCompleted(object arg) {
            if ((this.buscarClientesDirectorioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarClientesDirectorioCompleted(this, new buscarClientesDirectorioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:procesoDIRWebServiceResultado.beans.ws.dir.ssicc.belcorp.biz")]
    public partial class ProcesoDIRWebServiceResultado {
        
        private ClienteDIRWebService[] clienteDIRWebServiceField;
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ClienteDIRWebService[] clienteDIRWebService {
            get {
                return this.clienteDIRWebServiceField;
            }
            set {
                this.clienteDIRWebServiceField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:clienteDIRWebService.beans.ws.dir.ssicc.belcorp.biz")]
    public partial class ClienteDIRWebService {
        
        private string cUBField;
        
        private string cUBJefeField;
        
        private string apeMatField;
        
        private string apePatField;
        
        private string cargoField;
        
        private string codCargoField;
        
        private string codClienteField;
        
        private string codGrupoFuncionalField;
        
        private string codNovedadField;
        
        private string codPaisField;
        
        private string codPerfilField;
        
        private string codPlanillaField;
        
        private string codRegionField;
        
        private string codRolField;
        
        private string codZonaField;
        
        private string codigoPeriodoField;
        
        private string desGrupoFuncionalField;
        
        private string desRegionField;
        
        private string desRelContractualField;
        
        private string desZonaField;
        
        private string estadoField;
        
        private string estadoCargoField;
        
        private string fecIngresoField;
        
        private string fechaFinField;
        
        private string fechaInicioField;
        
        private string generoField;
        
        private string jefeDirectoField;
        
        private string mailBelcorpField;
        
        private string nombresField;
        
        private string nroDocField;
        
        private string perfilField;
        
        private string puestoOrgField;
        
        private string rolField;
        
        private string telefCasaField;
        
        private string telefMovilField;
        
        private string usuarioRedField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string CUB {
            get {
                return this.cUBField;
            }
            set {
                this.cUBField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string CUBJefe {
            get {
                return this.cUBJefeField;
            }
            set {
                this.cUBJefeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string apeMat {
            get {
                return this.apeMatField;
            }
            set {
                this.apeMatField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string apePat {
            get {
                return this.apePatField;
            }
            set {
                this.apePatField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codCargo {
            get {
                return this.codCargoField;
            }
            set {
                this.codCargoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codCliente {
            get {
                return this.codClienteField;
            }
            set {
                this.codClienteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codGrupoFuncional {
            get {
                return this.codGrupoFuncionalField;
            }
            set {
                this.codGrupoFuncionalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codNovedad {
            get {
                return this.codNovedadField;
            }
            set {
                this.codNovedadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codPais {
            get {
                return this.codPaisField;
            }
            set {
                this.codPaisField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codPerfil {
            get {
                return this.codPerfilField;
            }
            set {
                this.codPerfilField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codPlanilla {
            get {
                return this.codPlanillaField;
            }
            set {
                this.codPlanillaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codRegion {
            get {
                return this.codRegionField;
            }
            set {
                this.codRegionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codRol {
            get {
                return this.codRolField;
            }
            set {
                this.codRolField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codZona {
            get {
                return this.codZonaField;
            }
            set {
                this.codZonaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigoPeriodo {
            get {
                return this.codigoPeriodoField;
            }
            set {
                this.codigoPeriodoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desGrupoFuncional {
            get {
                return this.desGrupoFuncionalField;
            }
            set {
                this.desGrupoFuncionalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desRegion {
            get {
                return this.desRegionField;
            }
            set {
                this.desRegionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desRelContractual {
            get {
                return this.desRelContractualField;
            }
            set {
                this.desRelContractualField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desZona {
            get {
                return this.desZonaField;
            }
            set {
                this.desZonaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estadoCargo {
            get {
                return this.estadoCargoField;
            }
            set {
                this.estadoCargoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecIngreso {
            get {
                return this.fecIngresoField;
            }
            set {
                this.fecIngresoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string jefeDirecto {
            get {
                return this.jefeDirectoField;
            }
            set {
                this.jefeDirectoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mailBelcorp {
            get {
                return this.mailBelcorpField;
            }
            set {
                this.mailBelcorpField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nroDoc {
            get {
                return this.nroDocField;
            }
            set {
                this.nroDocField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string perfil {
            get {
                return this.perfilField;
            }
            set {
                this.perfilField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string puestoOrg {
            get {
                return this.puestoOrgField;
            }
            set {
                this.puestoOrgField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefCasa {
            get {
                return this.telefCasaField;
            }
            set {
                this.telefCasaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefMovil {
            get {
                return this.telefMovilField;
            }
            set {
                this.telefMovilField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string usuarioRed {
            get {
                return this.usuarioRedField;
            }
            set {
                this.usuarioRedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void obtenerClientesDirectorioCompletedEventHandler(object sender, obtenerClientesDirectorioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerClientesDirectorioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerClientesDirectorioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcesoDIRWebServiceResultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcesoDIRWebServiceResultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void buscarClientesDirectorioCompletedEventHandler(object sender, buscarClientesDirectorioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarClientesDirectorioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarClientesDirectorioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcesoDIRWebServiceResultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcesoDIRWebServiceResultado)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591